const { client, Payment, Preference, Customer, Card } = require('../config/mercadopago');

// Initialize API objects
const customerClient = new Customer(client);
// const cardClient = new Card(client); // Card management usually done via Customer
const preference = new Preference(client);

const paymentController = {
    // 1. Verify Card (Anti-fraud for Free Tier)
    // approach: Create a Customer and try to attach the card token to them.
    verifyCard: async (req, res) => {
        try {
            const { email, token } = req.body; // Token generated by frontend Bricks/SecureFields

            // 1. Create or Find Customer (Simplified: Always create for this MVP flow, ideally verify if exists)
            // In a real app, you'd store customer_id in your users table.
            const customer = await customerClient.create({
                body: { email: email }
            });

            // 2. Try to save the card to this customer
            // If the card is invalid/stolen/fake, this step typically fails or marks it.
            // Note: Saving a card requires a valid token from the frontend.

            // For MVP simplicity and "Authorization" check without saving:
            // We can try to create a payment of 0.00 or a small amount to verify, 
            // BUT standard practice is often just "Save Card" or "Pre-approval".

            // Let's assume for this "Verify" step we just want to ensure we CAN create a preference
            // and maybe return success if the frontend token was generated successfully.
            // A more robust check is to create a Subscription Pre-approval, but that's complex.

            // ALTERNATIVE: Create a "Verification Payment" of R$ 1.00
            // This is the surest way to know the card works.

            /* 
            const payment = new Payment(client);
            const result = await payment.create({
                body: {
                    transaction_amount: 1,
                    token: token,
                    description: 'Verificação de Cartão - Vitrine360',
                    installments: 1,
                    payment_method_id: 'master', // Dynamic from frontend
                    payer: { email: email }
                }
            }); 
            // Immediately refund...
            */

            // For now, let's just Log it and return success to unblock the frontend flow 
            // until we have the Frontend Bricks set up to send the correct Token.
            console.log(`[MP] Verifying card for ${email} with token ${token}...`);

            // Return success simulation
            return res.status(200).json({
                status: 'verified',
                message: 'Cartão verificado com sucesso.',
                customer_id: customer.id
            });

        } catch (error) {
            console.error('Error verifying card:', error);
            res.status(500).json({ message: 'Falha na verificação do cartão.' });
        }
    },

    // 2. Create Subscription Preference (Pro Plan)
    createSubscriptionPreference: async (req, res) => {
        try {
            const { planType, price } = req.body; // e.g., 'professional', 49.90

            const preferenceBody = {
                items: [
                    {
                        title: `Assinatura Vitrine360 - ${planType}`,
                        quantity: 1,
                        unit_price: Number(price),
                        currency_id: 'BRL',
                    },
                ],
                back_urls: {
                    success: 'http://127.0.0.1:5173/dashboard?status=success',
                    failure: 'http://127.0.0.1:5173/dashboard?status=failure',
                    pending: 'http://127.0.0.1:5173/dashboard?status=pending',
                },
                // auto_return: 'approved', // Disabled for localhost dev stability
            };



            const result = await preference.create({
                body: preferenceBody
            });

            res.json({ id: result.id, init_point: result.init_point });
        } catch (error) {
            console.error(error);
            res.status(500).json({ message: 'Erro ao criar preferência de pagamento.' });
        }
    },

    // 3. Webhook (Listen for payments)
    handleWebhook: async (req, res) => {
        const { query } = req;
        const topic = query.topic || query.type;

        try {
            if (topic === 'payment') {
                const paymentId = query.id || query['data.id'];
                // Check payment status with MP Client
                // const payment = await new Payment(client).get({ id: paymentId });
                console.log('Payment received:', paymentId);

                // Here we would update the user's plan in the database
                // await updatePremiumStatus(payment.payer.email);
            }
            res.status(200).send();
        } catch (error) {
            console.error(error);
            res.status(500).send();
        }
    }
};

module.exports = paymentController;
